services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: 'GMT+2' # Set timezone to France
      PGTZ: 'GMT+2' # We need to set both TZ and PGTZ (c.f. https://stackoverflow.com/questions/44394295)
    healthcheck:
      test: 'psql -c "select 1" -d $$POSTGRES_DB || exit 0'
      interval: 1s
      timeout: 20s
      retries: 20
      start_period: 1s
